version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
s3_prefix = "sam-app"
resolve_s3 = true
region = "ap-northeast-1"
confirm_changeset = true
no_fail_on_empty_changeset = true
capabilities = "CAPABILITY_IAM"