AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  SSMParameterName:
    Type: String
    Default: '/app/server/dotenv'
    Description: 'SSM Parameter Store name for dotenv file'
  NetworkStackName:
    Type: String
    Default: 'network'
    Description: 'Name of the network stack'
  RDSStackName:
    Type: String
    Default: 'rds'
    Description: 'Name of the RDS stack'
  S3StackName:
    Type: String
    Default: 's3'
    Description: 'Name of the S3 stack'
  SNSStackName:
    Type: String
    Default: 'sns'
    Description: 'Name of the SNS stack'
  SQSStackName:
    Type: String
    Default: 'sqs'
    Description: 'Name of the SQS stack'

Globals:
  Function:
    MemorySize: 128
    Tracing: Active
    Timeout: 900
    VpcConfig:
      SecurityGroupIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-LambdaSecurityGroupId'
      SubnetIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet1Id'
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet2Id'
    Environment:
      Variables:
        WITH_LAMBDA: "true"
        SSM_DOTENV_PARAMETER_NAME: !Ref SSMParameterName
        DATABASE_URL:
          Fn::ImportValue: !Sub '${RDSStackName}-ConnectionString'
        S3_BUCKET_NAME:
          Fn::ImportValue: !Sub '${S3StackName}-S3BucketName'
        SNS_ASYNC_TASK_TOPIC_ARN:
          Fn::ImportValue: !Sub '${SNSStackName}-AsyncTaskTopicArn'
        SQS_ASYNC_TASK_QUEUE_URL:
          Fn::ImportValue: !Sub '${SQSStackName}-AsyncTaskQueueUrl'
        COGNITO_ADMIN_USER_POOL_ID:
          Fn::ImportValue: !Sub '${CognitoStackName}-CognitoAdminUserPoolId'

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
      Policies:
        - VPCAccessPolicy: { }
        - AmazonSSMReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AmazonSNSFullAccess
        - LambdaInvokePolicy:
            FunctionName: "*"
    Metadata:
      BuildMethod: makefile

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      BinaryMediaTypes:
        - "*/*"

  AsyncSnsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      Events:
        Topic:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: !Sub '${SNSStackName}-AsyncTaskTopicArn'
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Policies:
        - VPCAccessPolicy: { }
        - AmazonSSMReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AmazonSNSFullAccess
        - LambdaInvokePolicy:
            FunctionName: "*"
    Metadata:
      BuildMethod: makefile

  AsyncSqsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::ImportValue: !Sub '${SQSStackName}-AsyncTaskQueueArn'
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
            ScalingConfig:
              MaximumConcurrency: 10
      Policies:
        - VPCAccessPolicy: { }
        - AmazonSSMReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AmazonSNSFullAccess
        - LambdaInvokePolicy:
            FunctionName: "*"
    Metadata:
      BuildMethod: makefile

  SyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      Policies:
        - VPCAccessPolicy: { }
        - AmazonSSMReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AmazonSNSFullAccess
        - LambdaInvokePolicy:
            FunctionName: "*"
    Metadata:
      BuildMethod: makefile

  BatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Enabled: true
            Input: '{}'
            Schedule: 'rate(10 minutes)'
      Policies:
        - VPCAccessPolicy: { }
        - AmazonSSMReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AmazonSNSFullAccess
        - LambdaInvokePolicy:
            FunctionName: "*"
    Metadata:
      BuildMethod: makefile


Outputs:
  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/api/'

  ApiFunctionArn:
    Description: 'API Function ARN'
    Value: !GetAtt ApiFunction.Arn

  AsyncSnsFunctionArn:
    Description: 'Async SNS Function ARN'
    Value: !GetAtt AsyncSnsFunction.Arn

  AsyncSqsFunctionArn:
    Description: 'Async SQS Function ARN'
    Value: !GetAtt AsyncSqsFunction.Arn

  SyncFunctionArn:
    Description: 'Sync Function ARN'
    Value: !GetAtt SyncFunction.Arn

  BatchFunctionArn:
    Description: 'Batch Function ARN'
    Value: !GetAtt BatchFunction.Arn

