AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  NetworkStackName:
    Type: String
    Default: 'network'

Resources:
  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.nano
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      SubnetId:
        Fn::ImportValue: !Sub '${NetworkStackName}-Subnet1Id'
      SecurityGroupIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-BastionSecurityGroupId'
      Tags:
        - Key: Name
          Value: bastion

Outputs:
  BastionInstanceId:
    Value: !Ref BastionInstance