AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL for development environment'

Parameters:
  NetworkStackName:
    Type: String
    Default: 'network'
    Description: 'Name of the network stack'
  DBPassword:
    Type: String
    Default: 'postgres'
    Description: 'Database password'
    NoEcho: true
  DeletionProtection:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: 'Enable deletion protection for the RDS instance'
  MultipleAZ:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: 'Enable Multi-AZ'
  DBInstanceClass:
    Type: String
    Default: 'db.t3.micro'
    AllowedValues:
      - 'db.t3.micro'
      - 'db.t3.small'
      - 'db.t3.medium'
      - 'db.t3.large'
      - 'db.r5.large'
      - 'db.r5.xlarge'
    Description: 'DB instance class'

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'Subnet group for RDS PostgreSQL'
      SubnetIds:
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet1Id'
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet2Id'
      Tags:
        - Key: Name
          Value: rds-postgres-subnet-group

  PostgreSQLDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: postgres-rds
      DBName: app
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '17'
      MasterUsername: postgres
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      StorageType: gp2
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub '${NetworkStackName}-RDSSecurityGroupId'
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      MultiAZ: !Ref MultipleAZ
      StorageEncrypted: true
      DeletionProtection: !Ref DeletionProtection
      Tags:
        - Key: Name
          Value: postgres

Outputs:
  DatabaseEndpoint:
    Description: 'RDS PostgreSQL Endpoint'
    Value: !GetAtt PostgreSQLDatabase.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseEndpoint'

  DatabasePort:
    Description: 'RDS PostgreSQL Port'
    Value: !GetAtt PostgreSQLDatabase.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-DatabasePort'

  ConnectionString:
    Description: 'PostgreSQL Connection String'
    Value: !Sub 'postgresql://postgres:${DBPassword}@${PostgreSQLDatabase.Endpoint.Address}:${PostgreSQLDatabase.Endpoint.Port}/app'
    Export:
      Name: !Sub '${AWS::StackName}-ConnectionString'