[package]
name = "async_task"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
tokio = { version = "1", features = ["full"] }
lambda_runtime = "0.14"
anyhow = "1.0"
serde_json = "1.0"
